---
apiVersion: v1
kind: Service
metadata:
  name: openmrsapp
  labels:
    run: openmrsapp
spec:
  type: NodePort
  selector:
    run: openmrsapp
  ports:
    - name: http
      port: 9999
      targetPort: 8080
      protocol: TCP
